from __future__ import annotations

from datetime import datetime, timedelta, timezone

from ..connection import get_db

# Seeds settings.generated_chars from the rows that already exist the first
# time the counter is touched (NULL = never seeded). Assistant rows across ALL
# branches (swipes/regens are sibling rows) approximate what the LLM has
# generated historically; after this one-time backfill the counter only moves
# via add_generated_chars, so deleting conversations no longer shrinks it.
_SEED_GENERATED_CHARS_SQL = """
    UPDATE settings
    SET generated_chars = (
        SELECT COALESCE(SUM(LENGTH(content)), 0) FROM messages WHERE role = 'assistant'
    )
    WHERE id = 1 AND generated_chars IS NULL
"""


async def get_generated_chars() -> int:
    """Lifetime characters generated by the LLM (callers derive tokens).

    Seeds the counter from existing assistant messages on first use.
    """
    async with get_db() as db:
        await db.execute(_SEED_GENERATED_CHARS_SQL)
        await db.commit()
        rows = list(await db.execute_fetchall("SELECT generated_chars FROM settings WHERE id = 1"))
        return int(rows[0][0]) if rows and rows[0][0] is not None else 0


async def add_generated_chars(chars: int) -> None:
    """Credit *chars* of freshly generated text to the lifetime counter.

    Call AFTER the assistant message is persisted: if the counter was never
    seeded, the seed scan already counts that new row, so the increment is
    skipped for exactly that case (cur.rowcount == 1) to avoid double counting.
    """
    if chars <= 0:
        return
    async with get_db() as db:
        cur = await db.execute(_SEED_GENERATED_CHARS_SQL)
        if cur.rowcount == 0:
            await db.execute(
                "UPDATE settings SET generated_chars = generated_chars + ? WHERE id = 1",
                (chars,),
            )
        await db.commit()


async def get_global_stats() -> dict:
    """Aggregate usage stats across the whole database.

    Token totals are NOT derived here -- they come from the persistent
    ``generated_chars`` counter via :func:`get_generated_chars`.
    """
    async with get_db() as db:
        conv_row = list(await db.execute_fetchall("SELECT COUNT(*) FROM conversations"))
        total_conversations = conv_row[0][0] if conv_row else 0

        # One full scan of messages: the count covers ALL branches (swipes/regens
        # are sibling rows here), while user_chars filters to role='user' so
        # "words written" reflects only what the user typed.
        msg_row = list(
            await db.execute_fetchall(
                """SELECT COUNT(*),
                          COALESCE(SUM(CASE WHEN role = 'user' THEN LENGTH(content) ELSE 0 END), 0)
                   FROM messages"""
            )
        )
        total_messages = msg_row[0][0] if msg_row else 0
        user_chars = msg_row[0][1] if msg_row else 0

        # Favorite character = the one whose conversations hold the most messages.
        # Group on character_name (not card id) so renamed/deleted cards still tally,
        # skipping unnamed conversations.
        fav_row = list(
            await db.execute_fetchall(
                """SELECT c.character_name,
                          COUNT(*) AS msg_count,
                          COUNT(DISTINCT c.id) AS conv_count,
                          MAX(c.character_card_id) AS card_id
                   FROM messages m
                   JOIN conversations c ON c.id = m.conversation_id
                   WHERE c.character_name != ''
                   GROUP BY c.character_name
                   ORDER BY msg_count DESC
                   LIMIT 1"""
            )
        )
        favorite_character = (
            {
                "name": fav_row[0][0],
                "messages": fav_row[0][1],
                "conversations": fav_row[0][2],
                "card_id": fav_row[0][3],
            }
            if fav_row
            else None
        )

        # A random well-worn character (>100 messages) for the "misses you"
        # spotlight theme. Same shape as the favorite, but excludes the favorite
        # itself so the two themes stay distinct, and skips anyone talked to in
        # the last 24h — they can't "miss you" if you just spoke. created_at is
        # an ISO-8601 UTC string, so a string compare against the cutoff sorts
        # correctly. RANDOM() picks the candidate; the endpoint flips the coin
        # on which theme actually shows.
        fav_name = favorite_character["name"] if favorite_character else ""
        recent_cutoff = (datetime.now(timezone.utc) - timedelta(hours=24)).isoformat()
        missed_row = list(
            await db.execute_fetchall(
                """SELECT c.character_name,
                          COUNT(*) AS msg_count,
                          COUNT(DISTINCT c.id) AS conv_count,
                          MAX(c.character_card_id) AS card_id
                   FROM messages m
                   JOIN conversations c ON c.id = m.conversation_id
                   WHERE c.character_name != '' AND c.character_name != ?
                   GROUP BY c.character_name
                   HAVING COUNT(*) > 100 AND MAX(m.created_at) < ?
                   ORDER BY RANDOM()
                   LIMIT 1""",
                (fav_name, recent_cutoff),
            )
        )
        missed_character = (
            {
                "name": missed_row[0][0],
                "messages": missed_row[0][1],
                "conversations": missed_row[0][2],
                "card_id": missed_row[0][3],
            }
            if missed_row
            else None
        )

        # > 0 (not just IS NOT NULL): turns with no LLM passes log 0, and
        # averaging those in would understate true response time.
        lat_row = list(
            await db.execute_fetchall("SELECT AVG(agent_latency_ms) FROM conversation_logs WHERE agent_latency_ms > 0")
        )
        avg_latency = lat_row[0][0] if lat_row else None

        return {
            "total_conversations": total_conversations,
            "total_messages": total_messages,
            "user_chars": user_chars,
            "favorite_character": favorite_character,
            "missed_character": missed_character,
            "avg_latency_ms": avg_latency,
        }
